In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model  import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import matplotlib.pyplot as plt
# pandas configs
main_df = pd.read_csv("football.csv")
pd.set_option("display.max_columns", None)

In [3]:
def missing(main_df):
    missing_percentage = (main_df.isnull().sum() / len(main_df)) * 100
    missing_rows_per_column = main_df.isnull().sum()
    missing_df = pd.DataFrame({'Column_Name': main_df.columns,'Missing_Rows': missing_rows_per_column.values, 'Missing_Percentage': missing_percentage})
    missing_df = missing_df.sort_values(by='Missing_Percentage', ascending=False)
    pd.set_option('display.max_rows', None)
    columns_with_missing = missing_df[missing_df['Missing_Percentage'] > 0]
    display(columns_with_missing)
missing(main_df)

                               Column_Name  Missing_Rows  Missing_Percentage
nation_jersey_number  nation_jersey_number          7239           93.142048
goalkeeping_speed        goalkeeping_speed          7063           90.877509
player_tags                    player_tags          6900           88.780237
player_traits                player_traits          2901           37.326300
physic                              physic           709            9.122491
dribbling                        dribbling           709            9.122491
passing                            passing           709            9.122491
shooting                          shooting           709            9.122491
pace                                  pace           709            9.122491
defending                        defending           709            9.122491
release_clause_eur      release_clause_eur           466            5.995883
value_eur                        value_eur            66            0.849202
club_name                        club_name            61            0.784869
league_level                  league_level            61            0.784869
club_jersey_number      club_jersey_number            61            0.784869
club_team_id                  club_team_id            61            0.784869
wage_eur                          wage_eur            61            0.784869
league_name                    league_name            61            0.784869

In [4]:
req_col = ['overall',
 'potential',
 'weak_foot',
 'skill_moves',
 'pace',
 'shooting',
 'passing',
 'dribbling',
 'defending',
 'physic',
 'attacking_crossing',
 'attacking_finishing',
 'attacking_heading_accuracy',
 'attacking_short_passing',
 'attacking_volleys',
 'skill_dribbling',
 'skill_curve',
 'skill_fk_accuracy',
 'skill_long_passing',
 'skill_ball_control',
 'movement_acceleration',
 'movement_sprint_speed',
 'movement_agility',
 'movement_reactions',
 'movement_balance',
 'power_shot_power',
 'power_jumping',
 'power_stamina',
 'power_strength',
 'power_long_shots',
 'mentality_aggression',
 'mentality_interceptions',
 'mentality_positioning',
 'mentality_vision',
 'mentality_penalties',
 'mentality_composure',
 'defending_marking_awareness',
 'defending_standing_tackle',
 'defending_sliding_tackle',
 'goalkeeping_diving',
 'goalkeeping_handling',
 'goalkeeping_kicking',
 'goalkeeping_positioning',
 'goalkeeping_reflexes',
 'contribution_type'
]
main_df = main_df[req_col]
missing(main_df)

          Column_Name  Missing_Rows  Missing_Percentage
pace             pace           709            9.122491
shooting     shooting           709            9.122491
passing       passing           709            9.122491
dribbling   dribbling           709            9.122491
defending   defending           709            9.122491
physic         physic           709            9.122491

In [5]:
cols = ['dribbling','pace','physic','passing','shooting']
main_df[cols]=main_df[cols].fillna(main_df.mode().iloc[0])
main_df.dropna(inplace=True)
missing(main_df)

Empty DataFrame
Columns: [Column_Name, Missing_Rows, Missing_Percentage]
Index: []

In [7]:
X = main_df.drop(columns=['contribution_type'])
y = main_df['contribution_type']

# 80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)